In [1]:
import requests
import pandas as pd
from io import StringIO
from tqdm import tqdm
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

In [2]:
base = "https://stats.ncaa.org"
allteams = pd.read_html("https://stats.ncaa.org/selection_rankings/nitty_gritties/37268",extract_links='body')[0]

In [7]:
allRosters

,Date,Opponent,Result,Attendance,team,teamID
0,11/06/2023,Bradley,W 73-66,1203.0,Kansas City,/teams/560547
1,NaN,NaN,NaN,NaN,Kansas City,/teams/560547
2,11/11/2023,@ UTEP,L 60-62,1093.0,Kansas City,/teams/560547
3,NaN,NaN,NaN,NaN,Kansas City,/teams/560547
4,11/14/2023,Utah St.,L 60-62,462.0,Kansas City,/teams/560547
...,...,...,...,...,...,...
59,NaN,NaN,NaN,NaN,High Point,/teams/560554
60,03/09/2024,#5 Presbyterian 23-24 WBB Big South Tournament,L 50-59,1528.0,High Point,/teams/560554
61,NaN,NaN,NaN,NaN,High Point,/teams/560554
62,03/21/2024,@#4 Virginia 23-24 WBB WBIT,L 59-81,1883.0,High Point,/teams/560554
63,NaN,NaN,NaN,NaN,High Point,/teams/560554

In [13]:
allRosters = pd.DataFrame()
for team, teamid in tqdm(allteams.Team):
    roster = pd.read_html(base + teamid + '/roster')[0]
    roster['team']   = team
    roster['teamID'] = teamid.split('/')[2]

    allRosters = pd.concat([allRosters, roster])

100%|██████████| 360/360 [06:14<00:00,  1.04s/it]

In [14]:
# Save games data
allRosters.to_csv('rosters_2023_24.csv',index=False)

In [15]:
allRosters.loc[allRosters.duplicated('Name')].sort_values('Name')

,GP,GS,#,Name,Class,Position,Height,Hometown,High School,team,teamID
8,33,19,23,Aaliyah Moore,Jr.,F,6-1,"Moore, OK",Moore,Texas,561155
11,34,34,5,Destiny Jackson,Sr.,G,5-9,"Mansfield, TX",Mansfield Timberview,Rice,561041
8,26,15,33,Destiny Thomas,Sr.,F,6-2,"Atlanta, GA",Forest Park HS,Georgia,560774
11,26,0,25,Destiny Thomas,Fr.,G,5-10,"Paducah, KY",McCracken County HS,Murray St.,560923
3,30,17,10,Emily Jones,Jr.,G,5-10,"San Francisco, CA",Sacred Heart Cathedral Preparatory,Morgan St.,560918
11,29,14,15,Grace Hunter,Sr.,G,5-10,"Monroeville, IN",Bellmont HS,NIU,560979
0,19,0,2,Jada Brown,So.,G,5-8,"Bentonville, AR",Bentonville,Vanderbilt,561187
0,31,0,2,Jada Williams,Fr.,G,5-9,"Mason City, IA",Mason City,Milwaukee,561229
1,4,4,22,Jada Williams,Jr.,F,6-1,"Williamstown, NJ",Gloucester Catholic,Saint Peter's,561065
0,0,0,11,Kayla Cooper,So.,G,5-9,"Plano, TX",Plano East,Oklahoma,560999
5,11,0,4,Madison Greene,Fr.,G,5-6,"Columbus, OH",Pickerington Central,Vanderbilt,561187
11,33,0,2,Makayla Jackson,Fr.,G,5-8,"Alexandria, VA",Bullis School,Detroit Mercy,560719
5,29,1,14,Maliyah Johnson,Sr.,F,6-2,"Chicago, IL",NaN,Texas A&M,561146
8,26,12,2,Olivia Brown,Sr.,G,5-8,"East Grand Rapids, MI",East Grand Rapids,Valparaiso,561185
3,28,1,11,Olivia Smith,Sr.,F,6-1,"Las Vegas, NV",Bishop Gorman HS,CSUN,560650
2,25,17,1,Olivia Smith,So.,G,5-5,"Fort Wayne, IN",South Side,Eastern Mich.,560739
10,29,1,25,Taylor Smith,Fr.,F,6-2,"Pocatello, ID",Century,Weber St.,561207
8,19,5,3,Taylor Smith,Sr.,G,5-8,"Marietta, GA",Marietta HS,Xavier,561234
2,3,0,2,Taylor Williams,Sr.,G,5-10,"Daytona Beach, FL",Father Lopez Catholic HS,N.C. Central,560960
11,28,27,3,Taylor Williams,Sr.,F,5-8,"Rahway, NJ",NaN,Southern U.,561111